/**
 * Material Records Seed — 8 records (MAT-001 to MAT-008).
 *
 * Source of truth:
 *   - MAT-001 to MAT-004: full field data from hooomz_catalogue.jsx
 *   - MAT-005 to MAT-008: added in mat_browse.jsx
 *
 * IMPORTANT: linked_cost_items stores IDs only — never the old
 * "FLR-020 — Name" string format used in the JSX prototypes.
 *
 * MaterialRecord.tier = the tier THIS record IS. Separate record per tier.
 * (Unlike CostItem which has all three tiers as columns in one row.)
 *
 * photo_url: Supabase Storage URLs only — never base64 in IndexedDB.
 * Prototype Unsplash URLs are kept here as placeholders until replaced.
 */

import type { MaterialRecord } from '../types/catalogue.types';

const NOW = new Date().toISOString();

export const MATERIAL_RECORDS_SEED: MaterialRecord[] = [
  {
    id: 'MAT-001',
    name: 'COREtec Pro Plus Enhanced',
    brand: 'COREtec',
    sku: 'VV492-00162',
    category: 'LVP / LVT',
    subcategory: 'WPC Core',
    supplier: 'Home Depot',
    supplier_sku: '1001805793',
    cost_per_unit: 3.89,
    unit_type: 'sq ft',
    qty_per_box: '8 planks',
    coverage_per_box: '16.23',
    dimensions: '7" × 48" × 8mm',
    thickness: '8mm',
    material_composition: 'WPC rigid core',
    finish: 'Embossed in register',
    color_name: 'Welles Oak',
    color_code: 'VV492-00162',
    weight_per_unit: '',
    wear_rating: 'AC4 / 20mil',
    water_resistance: '100% waterproof',
    warranty_years: 'Limited lifetime',
    warranty_notes: 'Residential lifetime, Light commercial 10yr',
    fire_rating: '',
    install_method: 'Floating',
    subfloor_requirements: 'Flat to 3/16" per 10ft',
    acclimation_required: '48hr at room temp',
    install_notes: 'Stagger joints 6" minimum, maintain 3/8" expansion',
    maintenance_notes: 'No steam mop, damp mop only',
    cleaning_instructions: 'pH-neutral cleaner, no wax or polish',
    refinishable: 'No',
    manufacturer_url: 'https://www.coretecfloors.com',
    labs_status: 'reviewed',
    labs_notes: 'Strong seller. In stock at local HD.',
    linked_cost_items: ['FLR-020'],
    notes: 'Our top LVP rec for main floors.',
    photo_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&crop=center',
    tier: 'Better',
    style: 'Modern',
    source_verified: true,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-002',
    name: 'Muskoka Select Red Oak',
    brand: 'Lauzon',
    sku: 'LAU-RO325S',
    category: 'Solid Hardwood',
    subcategory: 'Select Grade',
    supplier: 'Canac',
    supplier_sku: '4421873',
    cost_per_unit: 7.20,
    unit_type: 'sq ft',
    qty_per_box: '',
    coverage_per_box: '24',
    dimensions: '¾" × 3¼"',
    thickness: '¾"',
    material_composition: 'Solid Red Oak',
    finish: 'UV-cured satin',
    color_name: 'Natural',
    color_code: 'N300',
    weight_per_unit: '',
    wear_rating: '',
    water_resistance: 'Not waterproof — no wet areas',
    warranty_years: '25',
    warranty_notes: '25yr finish, lifetime structural',
    fire_rating: '',
    install_method: 'Nail-down',
    subfloor_requirements: 'Plywood only, no concrete',
    acclimation_required: '72hr minimum',
    install_notes: 'Not suitable below grade or over radiant heat above 85°F',
    maintenance_notes: 'Refinishable 5–7 times',
    cleaning_instructions: 'Dry/damp mop, approved cleaner only',
    refinishable: 'Yes',
    manufacturer_url: 'https://www.lauzon.com',
    labs_status: 'reviewed',
    labs_notes: 'Quality product. Lead time 2 weeks from Canac.',
    linked_cost_items: ['FLR-015', 'FLR-016'],
    notes: '',
    photo_url: 'https://images.unsplash.com/photo-1615873968403-89e068629265?w=400&h=400&fit=crop&crop=center',
    tier: 'Best',
    style: 'Traditional',
    source_verified: true,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-003',
    name: 'Subway Tile 3×6 White Matte',
    brand: 'Olympia Tile',
    sku: 'OLY-SW36WM',
    category: 'Tile',
    subcategory: 'Ceramic Subway',
    supplier: 'Rona',
    supplier_sku: '0373422',
    cost_per_unit: 2.49,
    unit_type: 'sq ft',
    qty_per_box: '36 tiles',
    coverage_per_box: '5.38',
    dimensions: '3" × 6" × 9mm',
    thickness: '9mm',
    material_composition: 'Ceramic',
    finish: 'Matte glaze',
    color_name: 'Bright White',
    color_code: 'SW36WM',
    weight_per_unit: '',
    wear_rating: 'PEI 2 — wall/accent only',
    water_resistance: 'Non-porous ceramic',
    warranty_years: '',
    warranty_notes: '',
    fire_rating: '',
    install_method: 'Thin-set adhesive',
    subfloor_requirements: 'Must be waterproofed in wet areas',
    acclimation_required: 'N/A',
    install_notes: 'Use 1/16" spacers for traditional look. Allow 10% waste.',
    maintenance_notes: 'Seal grout annually in wet areas',
    cleaning_instructions: 'Mild soap and water',
    refinishable: 'N/A',
    manufacturer_url: 'https://www.olympiatile.com',
    labs_status: 'being_reviewed',
    labs_notes: 'Testing grout options. Checking 3 colour combos.',
    linked_cost_items: ['FLR-027', 'ACC-008'],
    notes: 'Classic option, always in stock.',
    photo_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop&crop=center',
    tier: 'Good',
    style: 'Basic',
    source_verified: false,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-004',
    name: 'Shaker 1-Panel Interior Door',
    brand: 'Metrie',
    sku: 'MET-SHK1P68',
    category: 'Interior Door',
    subcategory: 'Swing — Hollow Core',
    supplier: 'Rona',
    supplier_sku: '0891234',
    cost_per_unit: 89,
    unit_type: 'each',
    qty_per_box: '1',
    coverage_per_box: '',
    dimensions: '32" × 80"',
    thickness: '1⅜"',
    material_composition: 'Hollow core — HDF skin',
    finish: 'Primed, ready to paint',
    color_name: 'Primed White',
    color_code: '',
    weight_per_unit: '28 lbs',
    wear_rating: '',
    water_resistance: 'Interior only',
    warranty_years: '1',
    warranty_notes: '1yr manufacturing defect',
    fire_rating: '',
    install_method: 'Prehung or slab',
    subfloor_requirements: 'N/A',
    acclimation_required: 'N/A',
    install_notes: 'Allow 1/8" clearance sides, 3/4" bottom sweep clearance',
    maintenance_notes: 'Touch-up paint as needed',
    cleaning_instructions: 'Damp cloth, no abrasives',
    refinishable: 'N/A',
    manufacturer_url: 'https://www.metrie.com',
    labs_status: 'reviewed',
    labs_notes: 'Standard go-to for Good/Better tier.',
    linked_cost_items: ['TRM-011'],
    notes: 'Most popular. Keep 4 in stock.',
    photo_url: 'https://images.unsplash.com/photo-1558618047-f4e60ccd4e6a?w=400&h=400&fit=crop&crop=center',
    tier: 'Better',
    style: 'Craftsman',
    source_verified: true,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-005',
    name: 'Wide Plank LVP Premium',
    brand: 'LifeProof',
    sku: 'LP-WP12-8MM',
    category: 'LVP / LVT',
    subcategory: 'WPC Core',
    supplier: 'Home Depot',
    supplier_sku: '',
    cost_per_unit: 5.49,
    unit_type: 'sq ft',
    qty_per_box: '',
    coverage_per_box: '19.8',
    dimensions: '12" × 60" × 8mm',
    thickness: '8mm',
    material_composition: 'WPC rigid core',
    finish: '',
    color_name: '',
    color_code: '',
    weight_per_unit: '',
    wear_rating: '',
    water_resistance: '100% waterproof',
    warranty_years: '',
    warranty_notes: '',
    fire_rating: '',
    install_method: 'Floating',
    subfloor_requirements: '',
    acclimation_required: '',
    install_notes: '',
    maintenance_notes: '',
    cleaning_instructions: '',
    refinishable: 'No',
    manufacturer_url: '',
    labs_status: 'needs_review',
    labs_notes: '',
    linked_cost_items: ['FLR-020'],
    notes: '',
    photo_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=400&fit=crop&crop=center',
    tier: 'Best',
    style: 'Modern',
    source_verified: false,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-006',
    name: 'Flat 2-Step Baseboard',
    brand: 'Metrie',
    sku: 'MET-BS35F',
    category: 'Baseboard',
    subcategory: 'Primed MDF',
    supplier: 'Rona',
    supplier_sku: '',
    cost_per_unit: 1.10,
    unit_type: 'linear ft',
    qty_per_box: '',
    coverage_per_box: '',
    dimensions: '3½" × ½"',
    thickness: '½"',
    material_composition: 'Primed MDF',
    finish: 'Primed',
    color_name: '',
    color_code: '',
    weight_per_unit: '',
    wear_rating: '',
    water_resistance: 'Interior only',
    warranty_years: '',
    warranty_notes: '',
    fire_rating: '',
    install_method: 'Nail & caulk',
    subfloor_requirements: 'N/A',
    acclimation_required: 'N/A',
    install_notes: '',
    maintenance_notes: '',
    cleaning_instructions: '',
    refinishable: 'N/A',
    manufacturer_url: 'https://www.metrie.com',
    labs_status: 'reviewed',
    labs_notes: '',
    linked_cost_items: ['TRM-002'],
    notes: '',
    photo_url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&h=400&fit=crop&crop=center',
    tier: 'Good',
    style: 'Basic',
    source_verified: false,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-007',
    name: 'Tall Flat Baseboard',
    brand: 'Metrie',
    sku: 'MET-BS45T',
    category: 'Baseboard',
    subcategory: 'Primed MDF',
    supplier: 'Rona',
    supplier_sku: '',
    cost_per_unit: 1.65,
    unit_type: 'linear ft',
    qty_per_box: '',
    coverage_per_box: '',
    dimensions: '4½" × ½"',
    thickness: '½"',
    material_composition: 'Primed MDF',
    finish: 'Primed',
    color_name: '',
    color_code: '',
    weight_per_unit: '',
    wear_rating: '',
    water_resistance: 'Interior only',
    warranty_years: '',
    warranty_notes: '',
    fire_rating: '',
    install_method: 'Nail & caulk',
    subfloor_requirements: 'N/A',
    acclimation_required: 'N/A',
    install_notes: '',
    maintenance_notes: '',
    cleaning_instructions: '',
    refinishable: 'N/A',
    manufacturer_url: 'https://www.metrie.com',
    labs_status: 'needs_review',
    labs_notes: '',
    linked_cost_items: ['TRM-002'],
    notes: '',
    photo_url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=400&h=400&fit=crop&crop=center',
    tier: 'Better',
    style: 'Modern',
    source_verified: false,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'MAT-008',
    name: 'Large Format Porcelain 24×24',
    brand: 'Olympia Tile',
    sku: 'OLY-LF2424G',
    category: 'Tile',
    subcategory: 'Porcelain Large Format',
    supplier: 'Rona',
    supplier_sku: '',
    cost_per_unit: 6.99,
    unit_type: 'sq ft',
    qty_per_box: '',
    coverage_per_box: '16',
    dimensions: '24" × 24" × 10mm',
    thickness: '10mm',
    material_composition: 'Porcelain',
    finish: '',
    color_name: '',
    color_code: '',
    weight_per_unit: '',
    wear_rating: '',
    water_resistance: 'Non-porous porcelain',
    warranty_years: '',
    warranty_notes: '',
    fire_rating: '',
    install_method: 'Thin-set adhesive',
    subfloor_requirements: 'Must be waterproofed in wet areas',
    acclimation_required: 'N/A',
    install_notes: '',
    maintenance_notes: '',
    cleaning_instructions: '',
    refinishable: 'N/A',
    manufacturer_url: 'https://www.olympiatile.com',
    labs_status: 'being_reviewed',
    labs_notes: '',
    linked_cost_items: ['FLR-028'],
    notes: '',
    photo_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&crop=center',
    tier: 'Best',
    style: 'Modern',
    source_verified: false,
    division: 'interiors',
    createdAt: NOW,
    updatedAt: NOW,
  },
];
